set_property -dict {PACKAGE_PIN P17 IOSTANDARD LVCMOS33} [get_ports clk]
set_property -dict {PACKAGE_PIN P15 IOSTANDARD LVCMOS33} [get_ports rst_n]



set_property -dict {PACKAGE_PIN R15 IOSTANDARD LVCMOS33} [get_ports key_time_base]
set_property -dict {PACKAGE_PIN V1 IOSTANDARD LVCMOS33} [get_ports key_left]
set_property -dict {PACKAGE_PIN R11 IOSTANDARD LVCMOS33} [get_ports key_right]
set_property -dict {PACKAGE_PIN G17 IOSTANDARD LVCMOS33} [get_ports key_hz]
set_property -dict {PACKAGE_PIN B17 IOSTANDARD LVCMOS33} [get_ports key_khz]

set_property -dict {PACKAGE_PIN G1 IOSTANDARD LVCMOS33} [get_ports {seg_en0[3]}]
set_property -dict {PACKAGE_PIN F1 IOSTANDARD LVCMOS33} [get_ports {seg_en0[2]}]
set_property -dict {PACKAGE_PIN E1 IOSTANDARD LVCMOS33} [get_ports {seg_en0[1]}]
set_property -dict {PACKAGE_PIN G6 IOSTANDARD LVCMOS33} [get_ports {seg_en0[0]}]

set_property -dict {PACKAGE_PIN D4 IOSTANDARD LVCMOS33} [get_ports {seg_code0[0]}]
set_property -dict {PACKAGE_PIN E3 IOSTANDARD LVCMOS33} [get_ports {seg_code0[1]}]
set_property -dict {PACKAGE_PIN D3 IOSTANDARD LVCMOS33} [get_ports {seg_code0[2]}]
set_property -dict {PACKAGE_PIN F4 IOSTANDARD LVCMOS33} [get_ports {seg_code0[3]}]
set_property -dict {PACKAGE_PIN F3 IOSTANDARD LVCMOS33} [get_ports {seg_code0[4]}]
set_property -dict {PACKAGE_PIN E2 IOSTANDARD LVCMOS33} [get_ports {seg_code0[5]}]
set_property -dict {PACKAGE_PIN D2 IOSTANDARD LVCMOS33} [get_ports {seg_code0[6]}]
set_property -dict {PACKAGE_PIN H2 IOSTANDARD LVCMOS33} [get_ports {seg_code0[7]}]



set_property IOSTANDARD LVCMOS33 [get_ports dac_clk_out]
set_property PACKAGE_PIN H17 [get_ports dac_clk_out]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data_out[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data_out[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data_out[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data_out[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data_out[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data_out[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data_out[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data_out[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data_out[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data_out[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data_out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data_out[0]}]


set_property PACKAGE_PIN H1 [get_ports {seg_en1[0]}]
set_property PACKAGE_PIN C1 [get_ports {seg_en1[1]}]
set_property PACKAGE_PIN C2 [get_ports {seg_en1[2]}]
set_property PACKAGE_PIN G2 [get_ports {seg_en1[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_en1[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_en1[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_en1[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_en1[0]}]

set_property -dict {PACKAGE_PIN B4 IOSTANDARD LVCMOS33} [get_ports {seg_code1[0]}]
set_property -dict {PACKAGE_PIN A4 IOSTANDARD LVCMOS33} [get_ports {seg_code1[1]}]
set_property -dict {PACKAGE_PIN A3 IOSTANDARD LVCMOS33} [get_ports {seg_code1[2]}]
set_property -dict {PACKAGE_PIN B1 IOSTANDARD LVCMOS33} [get_ports {seg_code1[3]}]
set_property -dict {PACKAGE_PIN A1 IOSTANDARD LVCMOS33} [get_ports {seg_code1[4]}]
set_property -dict {PACKAGE_PIN B3 IOSTANDARD LVCMOS33} [get_ports {seg_code1[5]}]
set_property -dict {PACKAGE_PIN B2 IOSTANDARD LVCMOS33} [get_ports {seg_code1[6]}]
set_property -dict {PACKAGE_PIN D5 IOSTANDARD LVCMOS33} [get_ports {seg_code1[7]}]

set_property PACKAGE_PIN P5 [get_ports {sw_type[1]}]
set_property PACKAGE_PIN P4 [get_ports {sw_type[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw_type[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw_type[0]}]


set_property PACKAGE_PIN N4 [get_ports {sw_mode[1]}]
set_property PACKAGE_PIN R1 [get_ports {sw_mode[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw_mode[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw_mode[0]}]




set_property -dict {PACKAGE_PIN D7 IOSTANDARD LVCMOS33} [get_ports vga_hs]
set_property -dict {PACKAGE_PIN C4 IOSTANDARD LVCMOS33} [get_ports vga_vs]

set_property -dict {PACKAGE_PIN F5 IOSTANDARD LVCMOS33} [get_ports {vga_rgb[0]}]
set_property -dict {PACKAGE_PIN C6 IOSTANDARD LVCMOS33} [get_ports {vga_rgb[1]}]
set_property -dict {PACKAGE_PIN C5 IOSTANDARD LVCMOS33} [get_ports {vga_rgb[2]}]
set_property -dict {PACKAGE_PIN B7 IOSTANDARD LVCMOS33} [get_ports {vga_rgb[3]}]
set_property -dict {PACKAGE_PIN B6 IOSTANDARD LVCMOS33} [get_ports {vga_rgb[4]}]
set_property -dict {PACKAGE_PIN A6 IOSTANDARD LVCMOS33} [get_ports {vga_rgb[5]}]
set_property -dict {PACKAGE_PIN A5 IOSTANDARD LVCMOS33} [get_ports {vga_rgb[6]}]
set_property -dict {PACKAGE_PIN D8 IOSTANDARD LVCMOS33} [get_ports {vga_rgb[7]}]
set_property -dict {PACKAGE_PIN C7 IOSTANDARD LVCMOS33} [get_ports {vga_rgb[8]}]
set_property -dict {PACKAGE_PIN E6 IOSTANDARD LVCMOS33} [get_ports {vga_rgb[9]}]
set_property -dict {PACKAGE_PIN E5 IOSTANDARD LVCMOS33} [get_ports {vga_rgb[10]}]
set_property -dict {PACKAGE_PIN E7 IOSTANDARD LVCMOS33} [get_ports {vga_rgb[11]}]


set_property IOSTANDARD LVCMOS33 [get_ports adc_clk]
set_property PACKAGE_PIN B13 [get_ports {adc_data_in[7]}]
set_property PACKAGE_PIN F14 [get_ports {adc_data_in[6]}]
set_property PACKAGE_PIN F13 [get_ports {adc_data_in[5]}]
set_property PACKAGE_PIN A18 [get_ports {adc_data_in[4]}]
set_property PACKAGE_PIN B18 [get_ports {adc_data_in[3]}]
set_property PACKAGE_PIN A14 [get_ports {adc_data_in[2]}]
set_property PACKAGE_PIN A13 [get_ports {adc_data_in[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_data_in[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_data_in[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_data_in[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_data_in[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_data_in[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_data_in[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_data_in[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_data_in[0]}]

set_property PACKAGE_PIN B11 [get_ports {adc_data_in[11]}]
set_property PACKAGE_PIN C14 [get_ports {adc_data_in[10]}]
set_property PACKAGE_PIN D14 [get_ports {adc_data_in[9]}]
set_property PACKAGE_PIN B14 [get_ports {adc_data_in[8]}]
set_property PACKAGE_PIN A16 [get_ports {adc_data_in[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_data_in[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_data_in[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_data_in[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_data_in[8]}]
set_property PACKAGE_PIN A15 [get_ports adc_clk]
set_property PACKAGE_PIN J13 [get_ports {dac_data_out[13]}]
set_property PACKAGE_PIN K13 [get_ports {dac_data_out[12]}]
set_property PACKAGE_PIN D17 [get_ports {dac_data_out[11]}]
set_property PACKAGE_PIN E17 [get_ports {dac_data_out[10]}]
set_property PACKAGE_PIN G14 [get_ports {dac_data_out[9]}]
set_property PACKAGE_PIN H14 [get_ports {dac_data_out[8]}]
set_property PACKAGE_PIN F16 [get_ports {dac_data_out[7]}]
set_property PACKAGE_PIN F15 [get_ports {dac_data_out[6]}]
set_property PACKAGE_PIN G16 [get_ports {dac_data_out[5]}]
set_property PACKAGE_PIN H16 [get_ports {dac_data_out[4]}]
set_property PACKAGE_PIN C15 [get_ports {dac_data_out[3]}]
set_property PACKAGE_PIN D15 [get_ports {dac_data_out[2]}]
set_property PACKAGE_PIN E16 [get_ports {dac_data_out[1]}]
set_property PACKAGE_PIN E15 [get_ports {dac_data_out[0]}]

set_property PACKAGE_PIN A11 [get_ports key_shihz]
set_property PACKAGE_PIN B16 [get_ports key_baikhz]
set_property PACKAGE_PIN U4 [get_ports key_up]
set_property PACKAGE_PIN R17 [get_ports key_down]
set_property IOSTANDARD LVCMOS33 [get_ports key_down]
set_property IOSTANDARD LVCMOS33 [get_ports key_baikhz]
set_property IOSTANDARD LVCMOS33 [get_ports key_shihz]
set_property IOSTANDARD LVCMOS33 [get_ports key_up]
